version: "3.8"
services:
  app:
    image: usanzadunje/laravel-dev
    container_name: app_container
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: php artisan serve --host=0.0.0.0 --port=80

  queue:
    image: usanzadunje/laravel-dev
    container_name: queue_worker_container
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: php artisan queue:listen

  npm:
    image: node:16-alpine
    container_name: npm_container
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - "3000:3000"
      - "3001:3001"
    # command: npm run watch for webpack
    command: npm run dev

  db:
    image: mysql:5.7
    container_name: db_container
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_NAME: mysql

volumes:
  mysql-data:
